### ISSUE TITLE
"()"単体で発言した場合、エラーが発生する。

### ISSUE THREAD

**Issue by Laica-Lunasys** [ucchyocean/LunaChat#134]
LunaChat ver 2.7.1にて、
チャットで () と発言すると、()をJapanize変換しようとするため、エラーが発生する様です。
()単体の場合はJapanizeから除外する必要があるかと思います。

**Comment by ucchyocean** [comment]
GoogleIMEですか？
SocialIMEですか？

**Comment by Laica-Lunasys** [comment]
GoogleIMEで発現されるバグです。
SocialIMEでは試していませんが、恐らくHTTPで行っていると思いますので同じかなと思います。

**Comment by ucchyocean** [comment]
GoogleIMEでのみ再現しますね。
SocialIMEでは再現しないようです。

------

<pre>
[12:55:59] [pool-3-thread-3/WARN]: java.io.FileNotFoundException: http://www.google.com/transliterate?langpair=ja-Hira|ja&text=
[12:55:59] [pool-3-thread-3/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[12:55:59] [pool-3-thread-3/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[12:55:59] [pool-3-thread-3/WARN]: 	at com.github.ucchyocean.lc.japanize.IMEConverter.conv(IMEConverter.java:70)
[12:55:59] [pool-3-thread-3/WARN]: 	at com.github.ucchyocean.lc.japanize.IMEConverter.convByGoogleIME(IMEConverter.java:35)
[12:55:59] [pool-3-thread-3/WARN]: 	at com.github.ucchyocean.lc.channel.DelayedJapanizeConvertTask.runSync(DelayedJapanizeConvertTask.java:106)
[12:55:59] [pool-3-thread-3/WARN]: 	at com.github.ucchyocean.lc.channel.DelayedJapanizeChannelChatTask.run(DelayedJapanizeChannelChatTask.java:42)
[12:55:59] [pool-3-thread-3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
[12:55:59] [pool-3-thread-3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:55:59] [pool-3-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:55:59] [pool-3-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:55:59] [pool-3-thread-3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:55:59] [pool-3-thread-3/INFO]: [G]ucchy: () ()
</pre>

-----

これは、KanaConverter が「(」や「)」を消去する仕様になっており、
https://github.com/ucchyocean/LunaChat/blob/master/src/main/java/com/github/ucchyocean/lc/japanize/KanaConverter.java#L153-L154
「()」だけ発言すると、からっぽの文字列をGoogleIMEに変換依頼してしまい、GoogleIMEはからっぽの文字列が来た時に何も応答を返さない仕様になっているからですね。
SocialIMEは、からっぽの文字列が依頼されても、とりあえず応答は返すようです（もちろん、応答内容はからっぽですけれども）。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
