### ISSUE TITLE
Windows環境の CraftBukkit 1.9 または spigot 1.9 で起動させると、エラーが起こって動作しない

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/LunaChat#141]
フォーラムにて報告された不具合。

-----

今回、spigot1.9にてチャットが日本語化されない問題が発生しております。
1.9はサポートされていないのは承知ですが、是非対応お願いします<m(__)m>

LunaChat:v2.7.5

起動時のエラーログ
<pre>
[06:08:31] [Server thread/ERROR]: Cannot load plugins/LunaChat/config.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xD81D) special characters are not allowed
in "'string'", position 121
 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:191) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:134) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:187) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at com.github.ucchyocean.lc.LunaChatConfig.reloadConfig(LunaChatConfig.java:156) [LunaChat.jar:?]
 at com.github.ucchyocean.lc.LunaChatConfig.<init>(LunaChatConfig.java:140) [LunaChat.jar:?]
 at com.github.ucchyocean.lc.LunaChat.onEnable(LunaChat.java:57) [LunaChat.jar:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
 at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 ... 18 more
[06:08:31] [Server thread/ERROR]: Cannot load plugins/LunaChat/messages.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xD8CA) special characters are not allowed
in "'string'", position 137
 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:191) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:134) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at com.github.ucchyocean.lc.Resources.initialize(Resources.java:44) [LunaChat.jar:?]
 at com.github.ucchyocean.lc.Resources.get(Resources.java:55) [LunaChat.jar:?]
 at com.github.ucchyocean.lc.channel.ChannelManager.<clinit>(ChannelManager.java:32) [LunaChat.jar:?]
 at com.github.ucchyocean.lc.LunaChat.onEnable(LunaChat.java:58) [LunaChat.jar:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
 at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
 ... 18 more
</pre>

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
