### ISSUE TITLE
HawkEyeと連携していると、チャンネルのログが記録されたときにエラーが記録される

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/LunaChat#143]
フォーラムにて報告された不具合。
HawkEyeと連携していると、チャンネルのログが記録されたときにエラーが記録されるようである。
こちらで確認した環境は、次の組み合わせ。

- spigot 1.9-R0.1
- LunaChat 2.8.1
- HawkEye 1.7.1
- MintChatBot 2.4.2

エラーが起こるときの条件と、エラーは、次の通り。

(1) チャンネルを作成して、そのチャンネルに入室しようとしたとき。
<pre>
[17:48:27] [Server thread/INFO]: ucchy issued server command: /ch create aaaa
[17:48:32] [Server thread/INFO]: ucchy issued server command: /ch join aaaa
[17:48:32] [Server thread/INFO]: [aaaa]ucchy さんがチャンネルに参加しました。
[17:48:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ch' in plugin LunaChat v2.8.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:44) ~[?:?]
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:38) ~[?:?]
	at com.github.ucchyocean.lc.bridge.HawkEyeBridge.writeLog(HawkEyeBridge.java:45) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.log(ChannelImpl.java:763) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.sendMessage(ChannelImpl.java:460) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.sendSystemMessage(ChannelImpl.java:303) ~[?:?]
	at com.github.ucchyocean.lc.channel.Channel.addMember(Channel.java:253) ~[?:?]
	at com.github.ucchyocean.lc.command.JoinCommand.runCommand(JoinCommand.java:229) ~[?:?]
	at com.github.ucchyocean.lc.command.LunaChatCommand.onCommand(LunaChatCommand.java:125) ~[?:?]
	at com.github.ucchyocean.lc.LunaChat.onCommand(LunaChat.java:136) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	... 15 more
</pre>

(2) ミントちゃん連携していて、チャンネルをブロードキャストに設定している状態で、ミントちゃんが応答を行ったとき。
<pre>
[17:50:52] [Craft Scheduler Thread - 0/INFO]: [aaaa]ミントちゃん@: ucchyさん、こんにちは！
[17:50:52] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[17:50:52] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin MintChatBot v2.4.2 generated an exception while executing task 36
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:44)
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:38)
	at com.github.ucchyocean.lc.bridge.HawkEyeBridge.writeLog(HawkEyeBridge.java:45)
	at com.github.ucchyocean.lc.channel.ChannelImpl.log(ChannelImpl.java:763)
	at com.github.ucchyocean.lc.channel.ChannelImpl.sendMessage(ChannelImpl.java:460)
	at com.github.ucchyocean.lc.channel.ChannelImpl.chatFromOtherSource(ChannelImpl.java:282)
	at com.github.ucchyocean.chatbot.bridge.LunaChatListener$1.run(LunaChatListener.java:89)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

</pre>

(3) Essentials を導入していて、OPの名前が赤くなる設定をしている状態で、OPがチャンネルで発言をしたとき。
<pre>
[17:50:51] [Async Chat Thread - #1/INFO]: [aaaa]ucchy: こんにちは
[17:50:51] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to LunaChat v2.8.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1272) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1210) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_77]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:44) ~[?:?]
	at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:38) ~[?:?]
	at com.github.ucchyocean.lc.bridge.HawkEyeBridge.writeLog(HawkEyeBridge.java:45) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.log(ChannelImpl.java:763) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.sendMessage(ChannelImpl.java:460) ~[?:?]
	at com.github.ucchyocean.lc.channel.ChannelImpl.chat(ChannelImpl.java:194) ~[?:?]
	at com.github.ucchyocean.lc.PlayerListener.processChatEvent(PlayerListener.java:225) ~[?:?]
	at com.github.ucchyocean.lc.PlayerListener.onAsyncPlayerChatHigh(PlayerListener.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-2038f4a-15222c8]
	... 11 more
</pre>
</pre>

**Comment by ucchyocean** [comment]
スタックトレースより、いずれも問題が起きている場所は一緒で、
<pre>
Caused by: java.lang.NullPointerException
    at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:44) ~[?:?]
    at uk.co.oliwali.HawkEye.util.HawkEyeAPI.addCustomEntry(HawkEyeAPI.java:38) ~[?:?]
</pre>
HawkEyeAPI#addCustomEntry メソッドを呼び出したときに問題がある模様。

**Comment by ucchyocean** [comment]
HawkEyeAPI#addCustomEntry メソッドの実装に変更があったようで、
パラメータ `addCustomEntry(String action, Player player, Location location, String data)` のいずれも、nullを指定したときに `throw new NullPointerException()` するように実装変更されていた。

LunaChat側の対応として、これらのパラメータがnullになる場合は、HawkEyeにログ記録しないように対応する。
特に、Locationがnullになるような場合（ミントちゃんの応答発言や、入退室メッセージなどのシステムメッセージ）は、今後はロギングしないようにする。
また、Essentialsで名前が赤くなったプレイヤーの発言がエラーになるのは、名前が解決できない（`&4ucchy`のようになっているから）プレイヤーの発言からLocationが取得できないからで、LunaChatのChannelPlayerをAPIに渡してなるべくLocationが取得できるように修正する必要がある。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![2016-04-16_18 20 18](https://cloud.githubusercontent.com/assets/2563444/14580186/21e7f5d8-0400-11e6-8c82-9539f29b0e7b.png)
