### ISSUE TITLE
LunaChat 2.8.2 と HawkEye 1.6.x を導入して、チャンネルチャットに発言すると、エラーが記録される。

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/LunaChat#144]
LunaChat 2.8.2 と HawkEye 1.6.1 の組み合わせで、かつ、チャンネルチャット機能を利用している場合に再現する。
通常チャットへの発言では再現しない。
また、LunaChat v2.8.1 以前や、HawkEye 1.6.2 以上の場合は、再現しない。
エラーの内容は次の通り。

<pre>
[17:04:27] [Server thread/INFO]: ucchy issued server command: /ch create test
[17:04:30] [Server thread/INFO]: ucchy issued server command: /ch join test
[17:04:30] [Server thread/INFO]: [test]ucchy さんがチャンネルに参加しました。
[17:04:31] [Craft Scheduler Thread - 0/INFO]: [test]ucchy: aiuep (アイウエp)
[17:04:31] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[17:04:31] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin LunaChat v2.8.2 generated an exception while executing task 7
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: uk.co.oliwali.HawkEye.util.HawkEyeAPI.addEntry(Luk/co/oliwali/HawkEye/entry/DataEntry;)Z
	at com.github.ucchyocean.lc.bridge.HawkEyeBridge.writeLog(HawkEyeBridge.java:38)
	at com.github.ucchyocean.lc.channel.ChannelImpl.log(ChannelImpl.java:759)
	at com.github.ucchyocean.lc.channel.ChannelImpl.sendMessage(ChannelImpl.java:460)
	at com.github.ucchyocean.lc.channel.DelayedJapanizeChannelChatTask.run(DelayedJapanizeChannelChatTask.java:45)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

</pre>

**Comment by ucchyocean** [comment]
Issue #143 修正時に、使用するHawkEye API を変更したが、このAPIは実は HawkEye 1.6.2 以降で追加されたものだった。
そのため、HawkEye 1.6.1 以前のバージョンを使用すると、APIが見つからずにエラーになる。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK。
- spigot 1.8.8 + HawkEye 1.6.0 + LunaChat 2.8.3
- spigot 1.9.4 + HawkEye 1.7.2 + LunaChat 2.8.3

の組み合わせでテストして、問題が無いことを確認した。
![2016-05-14_17 23 36](https://cloud.githubusercontent.com/assets/2563444/15267322/79ca6b1e-19f9-11e6-83ff-dda2468eaaf6.png)
![2016-05-14_17 25 50](https://cloud.githubusercontent.com/assets/2563444/15267324/859538de-19f9-11e6-9786-e5d1a08ed504.png)
