### ISSUE TITLE
Prism連携時に、LunaChatでNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/LunaChat#149]
フォーラムで報告をいただいた不具合。

StackTraceは下記の通り。
<pre>
[00:37:13] [Server thread/INFO]: [D]kotarobo_ さんがチャンネルチャットに参加しました。
[00:37:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ch' in plugin LunaChat v2.8.6
   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
   at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
   at com.github.ucchyocean.lc.channel.ChannelImpl.log(ChannelImpl.java:768) ~[?:?]
   at com.github.ucchyocean.lc.channel.ChannelImpl.sendMessage(ChannelImpl.java:460) ~[?:?]
   at com.github.ucchyocean.lc.channel.ChannelImpl.sendSystemMessage(ChannelImpl.java:303) ~[?:?]
   at com.github.ucchyocean.lc.channel.Channel.addMember(Channel.java:253) ~[?:?]
   at com.github.ucchyocean.lc.command.JoinCommand.runCommand(JoinCommand.java:229) ~[?:?]
   at com.github.ucchyocean.lc.command.LunaChatCommand.onCommand(LunaChatCommand.java:136) ~[?:?]
   at com.github.ucchyocean.lc.LunaChat.onCommand(LunaChat.java:144) ~[?:?]
   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
   ... 15 more
</pre>

**Comment by ucchyocean** [comment]
ChannelImpl.java:768行目は、Prism連携時にPrismにログを書き込む処理であり、チャンネルのシステムメッセージや、DiscordSRV連携しているときのDiscordからのメッセージが通過したときに、NullPointerExceptionが発生する。
システムメッセージなので、紐づくPlayerがnullになっているためである。
単純な、nullチェック漏れである。戒めて。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
