### ISSUE TITLE
configをリロード後、発言をするとエラーが発生する。

### ISSUE THREAD

**Issue by HinyariGohan** [ucchyocean/LunaChat#150]
config.ymlのnormalChatMessageFormatを変更後 */lc reload コマンドを用いてリロードをした。
その後発言するとエラーが発生する。

スタックトレース

>
[06:58:30 INFO]: Hinyari_Gohan issued server command: /lc reload
[06:58:32 ERROR]: Could not pass event AsyncPlayerChatEvent to LunaChat v2.8.8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1280) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1218) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_102]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.util.IllegalFormatConversionException: c != org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at com.github.ucchyocean.lc.PlayerListener.chatGlobal(PlayerListener.java:314) ~[?:?]
        at com.github.ucchyocean.lc.PlayerListener.processChatEvent(PlayerListener.java:233) ~[?:?]
        at com.github.ucchyocean.lc.PlayerListener.onAsyncPlayerChatHigh(PlayerListener.java:97) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        ... 11 more
[06:58:32 INFO]: <Hinyari_Gohan> a

config

> normalChatMessageFormat: '&6>>>&r %prefix%username &6>&r %msg'

**Comment by HinyariGohan** [comment]
エラーが発生しなくなった。

**Comment by ucchyocean** [comment]
normalChatMessageFormatに、定義されていない `%c` から始まるキーワードが誤って記載されていたため、問題が起きたようです。
config.yml を正しく書き換えした後、再度リロードしたため、再現しなくなったと推測されます。

本件は設定ミスなのでClosedでかまわないと思いますが、
今後は、設定ミスによる不要なエラーを減らすため、LunaChatで設定したキーワードを置き換えした後にnormalChatMessageFormatに残った `%` を消去する、などの対策を導入してもいいかも知れません。
別途、issueをあげて対応を検討します。
