### ISSUE TITLE
初期のconfig.yml/message.ymlがShift JISフォーマットで生成される

### ISSUE THREAD

**Issue by wataamewatagashi** [ucchyocean/LunaChat#167]
## 環境
- MCver: 1.7.10
- Server: Crucible 
- LunaChat v.2.8.14
## 内容
初期に生成されるファイルのフォーマットがShift JISになっており、その影響で設定の読み込みが不可能になっていました。
フォーマットを手動でUTF-8に変更したところ正常に読み込むことができました
#### 一応ですが該当エラーのログです↓
```sql
[13:40:30] [Server thread/INFO]: [LunaChat] Enabling LunaChat v2.8.14
[13:40:31] [Server thread/ERROR]: Cannot load plugins\LunaChat\config.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '?' (0x94) special characters are not allowed
in "'string'", position 177
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:52) ~[YamlConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:185) ~[FileConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:146) ~[FileConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:175) [YamlConfiguration.class:1.7.10-3.1]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:183) [JavaPlugin.class:1.7.10-3.1]
	at com.github.ucchyocean.lc.LunaChatConfig.reloadConfig(LunaChatConfig.java:168) [LunaChat.jar:?]
	at com.github.ucchyocean.lc.LunaChatConfig.<init>(LunaChatConfig.java:152) [LunaChat.jar:?]
	at com.github.ucchyocean.lc.LunaChat.onEnable(LunaChat.java:62) [LunaChat.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-3.1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [JavaPluginLoader.class:1.7.10-3.1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:428) [SimplePluginManager.class:1.7.10-3.1]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:463) [CraftServer.class:1.7.10-3.1]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:397) [CraftServer.class:1.7.10-3.1]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:523) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:497) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:457) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:651) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[ParserImpl$ParseImplicitDocumentStart.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[ParserImpl.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[ParserImpl.class:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107) ~[Composer.class:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[BaseConstructor.class:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Yaml.class:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[Yaml.class:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:50) ~[YamlConfiguration.class:1.7.10-3.1]
	... 18 more
[13:40:31] [Server thread/ERROR]: Cannot load plugins\LunaChat\messages.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '?' (0x82) special characters are not allowed
in "'string'", position 653
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:52) ~[YamlConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:185) ~[FileConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:146) ~[FileConfiguration.class:1.7.10-3.1]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:175) [YamlConfiguration.class:1.7.10-3.1]
	at com.github.ucchyocean.lc.Resources.initialize(Resources.java:44) [LunaChat.jar:?]
	at com.github.ucchyocean.lc.Resources.get(Resources.java:55) [LunaChat.jar:?]
	at com.github.ucchyocean.lc.channel.ChannelManager.<clinit>(ChannelManager.java:32) [LunaChat.jar:?]
	at com.github.ucchyocean.lc.LunaChat.onEnable(LunaChat.java:63) [LunaChat.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-3.1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [JavaPluginLoader.class:1.7.10-3.1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:428) [SimplePluginManager.class:1.7.10-3.1]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:463) [CraftServer.class:1.7.10-3.1]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:397) [CraftServer.class:1.7.10-3.1]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:523) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:497) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:457) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:651) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:1999) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1044) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:399) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[ScannerImpl.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[ParserImpl$ParseBlockMappingKey.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[ParserImpl.class:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[ParserImpl.class:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[Composer.class:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[Composer.class:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[Composer.class:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[Composer.class:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[BaseConstructor.class:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Yaml.class:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[Yaml.class:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:50) ~[YamlConfiguration.class:1.7.10-3.1]
	... 18 more
```

**Comment by ucchyocean** [comment]
#141 と同じ問題で、既に対応済みです。

Bukkit 1.9 の仕様変更で、以前はS-Jisエンコードでyamlが保存されていたのが、1.9以降でUTF-8になりました。
Bukkitをアップデートする場合は、設定ファイルを再生成するか、エンコードをUTF-8に変換して保存してください。
