### ISSUE TITLE
LunaChat v3.0でのConfig引き継ぎについて

### ISSUE THREAD

**Issue by tererun** [ucchyocean/LunaChat#171]
以前Spigotにて使っていたLunaChat(v2.8.12)のConfig類(plugins/LunaChat)をBungeeCord側に入れ、v3.0にて起動したところ、エラーが発生しました。

起動時のログ
<pre>
[17:49:01 ERROR]: java.io.IOException: Cannot load reader as yaml.
[17:49:01 ERROR]:       at com.github.ucchyocean.lc3.YamlConfig.load(YamlConfig.                                                                                                                                                             java:61)
[17:49:01 ERROR]:       at com.github.ucchyocean.lc3.YamlConfig.load(YamlConfig.                                                                                                                                                             java:70)
[17:49:01 ERROR]:       at com.github.ucchyocean.lc3.channel.ChannelManager.relo                                                                                                                                                             adAllData(ChannelManager.java:85)
[17:49:01 ERROR]:       at com.github.ucchyocean.lc3.channel.ChannelManager.<ini                                                                                                                                                             t>(ChannelManager.java:52)
[17:49:01 ERROR]:       at com.github.ucchyocean.lc3.LunaChatBungee.onEnable(Lun                                                                                                                                                             aChatBungee.java:56)
[17:49:01 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugin                                                                                                                                                             s(PluginManager.java:300)
[17:49:01 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[17:49:01 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLau                                                                                                                                                             ncher.java:62)
[17:49:01 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[17:49:01 WARN]: Exception encountered when loading plugin: LunaChat
java.lang.NullPointerException: null
        at com.github.ucchyocean.lc3.channel.ChannelManager.reloadAllData(Channe                                                                                                                                                             lManager.java:88) ~[?:?]
        at com.github.ucchyocean.lc3.channel.ChannelManager.<init>(ChannelManage                                                                                                                                                             r.java:52) ~[?:?]
        at com.github.ucchyocean.lc3.LunaChatBungee.onEnable(LunaChatBungee.java                                                                                                                                                             :56) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.                                                                                                                                                             java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall.jar                                                                                                                                                             :git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~                                                                                                                                                             [waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git                                                                                                                                                             :Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
</pre>

/lunachat reload時のエラーログ
<pre>
18:04:55 ERROR]: java.io.IOException: Cannot load reader as yaml.
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.YamlConfig.load(YamlConfig.java:61)
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.YamlConfig.load(YamlConfig.java:70)
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.channel.ChannelManager.reloadAllData(ChannelManager.java:85)
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.command.ReloadCommand.runCommand(ReloadCommand.java:77)
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.command.LunaChatCommand.execute(LunaChatCommand.java:89)
[18:04:55 ERROR]:       at com.github.ucchyocean.lc3.bungee.LunaChatCommandBungee.execute(LunaChatCommandBungee.java:42)
[18:04:55 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:197)
[18:04:55 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148)
[18:04:55 ERROR]:       at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:153)
[18:04:55 ERROR]:       at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60)
[18:04:55 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[18:04:55 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:04:55 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:04:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:04:55 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:04:55 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[18:04:55 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[18:04:55 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[18:04:55 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:04:55 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:04:55 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[18:04:55 WARN]: Error in dispatching command
java.lang.NullPointerException: null
        at com.github.ucchyocean.lc3.channel.ChannelManager.reloadAllData(ChannelManager.java:88) ~[?:?]
        at com.github.ucchyocean.lc3.command.ReloadCommand.runCommand(ReloadCommand.java:77) ~[?:?]
        at com.github.ucchyocean.lc3.command.LunaChatCommand.execute(LunaChatCommand.java:89) ~[?:?]
        at com.github.ucchyocean.lc3.bungee.LunaChatCommandBungee.execute(LunaChatCommandBungee.java:42) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:197) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:153) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
</pre>

**Comment by ucchyocean** [comment]
できればエラーが出ている config.yml も添付してほしいです。

**Comment by tererun** [comment]
すみません、添付を忘れていました。
一応セキュリティが怖いのでzipファイルにパスワードを付けましたので、うっちぃさんのTwitterのDMにパスワードを送らせていただきました。
[LunaChat.zip](https://github.com/ucchyocean/LunaChat/files/4791893/LunaChat.zip)

**Comment by ucchyocean** [comment]
データのご提供ありがとうございます。原因わかりました。
Yamlファイルの読み込みは、BukkitのYamlConfigurationをやめて、自分で作ったYamlローダーを使用しているのですが、からっぽのファイルがロードできない仕様になってしまっているようです。

この問題を一時的に回避するには、下記を試してみてください。
* LunaChatフォルダの下にあるいくつかの`.yml`ファイルのうち、0バイトのファイルを、すべて消去して、BungeeCordを起動し、これらのファイルを再生成してください。

本件は、自前のYamlローダーを改修し、からっぽのファイルもエラーにならずにロードできるように修正いたします。

**Comment by tererun** [comment]
改善しました、有難うございます。
