### ISSUE TITLE
LunaChat v3.0の全角スペースについて

### ISSUE THREAD

**Issue by tererun** [ucchyocean/LunaChat#172]
全角スペースを入力すると、

<pre>
[18:27:33 ERROR]: [/118.241.204.70:62798|K0ha] -> UpstreamBridge - encountered exception
java.lang.IllegalArgumentException: Chat message is empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:147) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
</pre>

というエラーの後、プレイヤーがキックされます。

**Comment by ucchyocean** [comment]
BungeeCord で再現調査をしてみましたが、いまのところ不具合が再現していません。

![2020-06-17_23 10 38](https://user-images.githubusercontent.com/2563444/84908919-0a51e400-b0f0-11ea-8418-c1c28d0b7824.png)

Waterfall特有の問題でしょうか？ Waterfallでも動かしてみましょうか。

**Comment by ucchyocean** [comment]
Waterfallを動かすと、不具合が再現しました。ですが、LunaChatを抜いても再現しますね。
LunaChat関係ないですね。Waterfallの問題でしょう。
ただ、LunaChatがChatEventに介在することで問題を回避することもできると思います。ちょっと検討してみます。

**Comment by tererun** [comment]
了解しました。ありがとうございます。

**Comment by ucchyocean** [comment]
Waterfallを検証してみましたが、ダメですね。プラグインにChatEventが流れてくるよりも前に、例外が発生してプレイヤーがキックされてしまっているようなので、LunaChatから何とかすることもできないです。
Waterfallへ不具合報告をして、直してもらわないと、どうにもならなさそうですね。。。

**Comment by ucchyocean** [comment]
既にイシューが発行されていて、プルリクエストも作成されているみたいです。Waterfallの対応待ちですね。
https://github.com/PaperMC/Waterfall/issues/413

**Comment by tererun** [comment]
ありがとうございます。
